 server {
    listen 80;
    server_name chetvertynivskyi.com www.chetvertynivskyi.com;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
    location ~ /\.(env|git|svn|hg) {
        deny all;
        return 404;
    }

    location ~* /(docker-compose\.ya?ml|\.env|\.git|terraform\.tfvars|terraform\.tfvars\.json|serverless\.ya?ml|vercel\.json|netlify\.toml|amplify\.ya?ml|debug\.log)$ {
        deny all;
        return 404;
    }
}

server {
    listen 443 ssl;
    server_name chetvertynivskyi.com www.chetvertynivskyi.com;

    ssl_certificate /etc/letsencrypt/live/chetvertynivskyi.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/chetvertynivskyi.com/privkey.pem;
    
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log warn;


    client_max_body_size 2M;
    
    location ~ /\.(env|git|svn|hg) {
        return 404;
    }

    location ~* /(docker-compose\.ya?ml|\.env|\.git|terraform\.tfvars|terraform\.tfvars\.json|serverless\.ya?ml|vercel\.json|netlify\.toml|amplify\.ya?ml|debug\.log)$ {
        return 404;
    }

    location / {
        proxy_pass http://frontend:3000;
        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    location /api/ {
        proxy_pass http://backend:5000;
        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
