version = 5.6.0
archive_dir = /etc/letsencrypt/archive/chetvertynivskyi.com
cert = /etc/letsencrypt/live/chetvertynivskyi.com/cert.pem
privkey = /etc/letsencrypt/live/chetvertynivskyi.com/privkey.pem
chain = /etc/letsencrypt/live/chetvertynivskyi.com/chain.pem
fullchain = /etc/letsencrypt/live/chetvertynivskyi.com/fullchain.pem
[renewalparams]
account = 9ae4bd8f72bf66d930e768fdf36f2534
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
chetvertynivskyi.com = /var/www/certbot
www.chetvertynivskyi.com = /var/www/certbot
